from fastapi import FastAPI
from sqlalchemy.orm import Session
from database import engine
import models


app = FastAPI()

models.Base.metadata.create_all(bind=engine)


@app.get("/skills")
def get_skills():
    return {"backend_skills": ["Python", "FastAPI", "SQLAlchemy"]}

@app.get("/update/{status}")
def save_status(status: str):
    with Session(engine) as session:
        new_log = models.StatusLog(status_text=status)

        session.add(new_log)
        session.commit()

    return {"message": f"Successfully saved: '{status}' to the database notebook!"}

@app.post("/logs")
def create_log(status: str):
    with Session(engine) as session:
        new_log = models.StatusLog(status_text=status)
        
        session.add(new_log)
        session.commit()

        # Refresh lets us read the new ID number generated by the database
        session.refresh(new_log)

    return {"message": "Created successfully!", "data": new_log}

@app.get("/history")
def get_all_logs():

    # Open up our pipeline session
    with Session(engine) as session:

        # Query the statusLog table and grab all records inside it
        all_records = session.query(models.StatusLog).all()

        # Hand the list of records back to the user
        return {"history_logbook": all_records}


@app.put("/logs/{log_id}")
def update_log(log_id: int, new_status: str):
    with Session(engine) as session:
        db_log = session.query(models.StatusLog).filter(models.StatusLog.id == log_id).first()

        # Safety check: if the id doesn't exist, tell the user
        if not db_log:
            return {"error": "Log record not found!"}
        
        # Change the text column to the new string provided by the user
        db_log.status_text = new_status

        session.commit()
        session.refresh(db_log)

        return {"message": "Updated successfully!", "updated data": db_log}


@app.delete("/logs/{log_id}")
def delete_log(log_id: int):
    with Session(engine) as session:
        # Use the log_id to fine the crate in the wharehouse
        db_log = session.query(models.StatusLog).filter(models.StatusLog.id == log_id).first()

        # Safety check: if it doesn't exist tell the user
        if not db_log:
            return {"errro": "log record not found!"}
        
        # Tell the session to delete that specific tracked object
        session.delete(db_log)

        # Lock the change into the database parmanently
        session.commit()

    return {"message": f"Log ID {log_id} has been parmenently deleted!"}